# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: On-Premises

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '-r win-x64 -c $(buildConfiguration) /p:PublishSingleFile=true --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: False
    includesymbols: False
    publishWebProjects: False
- task: CmdLine@2
  inputs:
    script: 'del SchedulesCli.pdb'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/OWLSchedules.zip'
    replaceExistingArchive: true
- task: CmdLine@2
  inputs:
    script: 'del SchedulesCli.exe'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'OWLSchedules'
    publishLocation: 'Container'

